var champions = [
  {
    Name: "Aatrox",
    Image: "Aatrox",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Darkin"],
    Resource: "Manaless",
    RangeType: ["Melee"],
    Region: ["Runeterra", "Shurima"],
    ReleaseYear: "2013",
  },
  {
    Name: "Ahri",
    Image: "Ahri",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Vastayan"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ionia"],
    ReleaseYear: "2011",
  },
  {
    Name: "Akali",
    Image: "Akali",
    Gender: "Female",
    Position: ["Middle", "Top"],
    Species: ["Human"],
    Resource: "Energy",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Akshan",
    Image: "Akshan",
    Gender: "Male",
    Position: ["Middle", "Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima"],
    ReleaseYear: "2021",
  },
  {
    Name: "Alistar",
    Image: "Alistar",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Minotaur"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Runeterra"],
    ReleaseYear: "2009",
  },
  {
    Name: "Amumu",
    Image: "Amumu",
    Gender: "Male",
    Position: ["Jungle", "Support"],
    Species: ["Undead", "Yordle"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shurima"],
    ReleaseYear: "2009",
  },
  {
    Name: "Anivia",
    Image: "Anivia",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["God", "Spirit"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Freljord"],
    ReleaseYear: "2009",
  },
  {
    Name: "Annie",
    Image: "Annie",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus", "Runeterra"],
    ReleaseYear: "2009",
  },
  {
    Name: "Aphelios",
    Image: "Aphelios",
    Gender: "Male",
    Position: ["Bottom"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Targon"],
    ReleaseYear: "2019",
  },
  {
    Name: "Ashe",
    Image: "Ashe",
    Gender: "Female",
    Position: ["Bottom", "Support"],
    Species: ["Human", "Iceborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Freljord"],
    ReleaseYear: "2009",
  },
  {
    Name: "Aurelion Sol",
    Image: "Aurelion Sol",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Celestial", "Dragon"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Runeterra", "Targon"],
    ReleaseYear: "2016",
  },
  {
    Name: "Azir",
    Image: "Azir",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["God-Warrior"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima"],
    ReleaseYear: "2014",
  },
  {
    Name: "Bard",
    Image: "Bard",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Celestial"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Runeterra"],
    ReleaseYear: "2015",
  },
  {
    Name: "Bel'Veth",
    Image: "Belveth",
    Gender: "Female",
    Position: ["Jungle"],
    Species: ["Void-Being"],
    Resource: "Manaless",
    RangeType: ["Melee"],
    Region: ["Void"],
    ReleaseYear: "2022",
  },
  {
    Name: "Blitzcrank",
    Image: "Blitzcrank",
    Gender: "Other",
    Position: ["Support"],
    Species: ["Golem"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Zaun"],
    ReleaseYear: "2009",
  },
  {
    Name: "Brand",
    Image: "Brand",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Freljord", "Runeterra"],
    ReleaseYear: "2011",
  },
  {
    Name: "Braum",
    Image: "Braum",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Human", "Iceborn"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2014",
  },
  {
    Name: "Caitlyn",
    Image: "Caitlyn",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Piltover"],
    ReleaseYear: "2011",
  },
  {
    Name: "Camille",
    Image: "Camille",
    Gender: "Female",
    Position: ["Top"],
    Species: ["Cyborg", "Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Piltover"],
    ReleaseYear: "2016",
  },
  {
    Name: "Cassiopeia",
    Image: "Cassiopeia",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus", "Shurima"],
    ReleaseYear: "2010",
  },
  {
    Name: "Cho'Gath",
    Image: "Chogath",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Void-Being"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Void"],
    ReleaseYear: "2009",
  },
  {
    Name: "Corki",
    Image: "Corki",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bandle City", "Piltover"],
    ReleaseYear: "2009",
  },
  {
    Name: "Darius",
    Image: "Darius",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Noxus"],
    ReleaseYear: "2012",
  },
  {
    Name: "Diana",
    Image: "Diana",
    Gender: "Female",
    Position: ["Jungle", "Middle"],
    Species: ["Aspect", "Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Targon"],
    ReleaseYear: "2012",
  },
  {
    Name: "Dr. Mundo",
    Image: "DrMundo",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Chemically Altered", "Human"],
    Resource: "Health costs",
    RangeType: ["Melee"],
    Region: ["Zaun"],
    ReleaseYear: "2009",
  },
  {
    Name: "Draven",
    Image: "Draven",
    Gender: "Male",
    Position: ["Bottom"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus"],
    ReleaseYear: "2012",
  },
  {
    Name: "Ekko",
    Image: "Ekko",
    Gender: "Male",
    Position: ["Jungle", "Middle"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Zaun"],
    ReleaseYear: "2015",
  },
  {
    Name: "Elise",
    Image: "Elise",
    Gender: "Female",
    Position: ["Jungle"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Melee", "Ranged"],
    Region: ["Noxus", "Shadow Isles"],
    ReleaseYear: "2012",
  },
  {
    Name: "Evelynn",
    Image: "Evelynn",
    Gender: "Female",
    Position: ["Jungle"],
    Species: ["Demon", "Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Runeterra"],
    ReleaseYear: "2009",
  },
  {
    Name: "Ezreal",
    Image: "Ezreal",
    Gender: "Male",
    Position: ["Bottom"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Piltover"],
    ReleaseYear: "2010",
  },
  {
    Name: "Fiddlesticks",
    Image: "Fiddlesticks",
    Gender: "Other",
    Position: ["Jungle"],
    Species: ["Demon", "Spirit"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Runeterra"],
    ReleaseYear: "2009",
  },
  {
    Name: "Fiora",
    Image: "Fiora",
    Gender: "Female",
    Position: ["Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Demacia"],
    ReleaseYear: "2012",
  },
  {
    Name: "Fizz",
    Image: "Fizz",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Bilgewater"],
    ReleaseYear: "2011",
  },
  {
    Name: "Galio",
    Image: "Galio",
    Gender: "Male",
    Position: ["Middle", "Support"],
    Species: ["Golem"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Demacia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Gankplank",
    Image: "Gankplank",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Bilgewater"],
    ReleaseYear: "2009",
  },
  {
    Name: "Garen",
    Image: "Garen",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human"],
    Resource: "Manaless",
    RangeType: ["Melee"],
    Region: ["Demacia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Gnar",
    Image: "Gnar",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Yordle"],
    Resource: "Rage",
    RangeType: ["Melee", "Ranged"],
    Region: ["Freljord"],
    ReleaseYear: "2014",
  },
  {
    Name: "Gragas",
    Image: "Gragas",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2010",
  },
  {
    Name: "Graves",
    Image: "Graves",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bilgewater"],
    ReleaseYear: "2011",
  },
  {
    Name: "Gwen",
    Image: "Gwen",
    Gender: "Female",
    Position: ["Top"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Camavor", "Shadow Isles"],
    ReleaseYear: "2021",
  },
  {
    Name: "Hecarim",
    Image: "Hecarim",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Undead"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Camavor", "Shadow Isles"],
    ReleaseYear: "2012",
  },
  {
    Name: "Heimerdinger",
    Image: "Heimerdinger",
    Gender: "Male",
    Position: ["Middle", "Support"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Piltover"],
    ReleaseYear: "2009",
  },
  {
    Name: "Illaoi",
    Image: "Illaoi",
    Gender: "Female",
    Position: ["Top"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Bilgewater"],
    ReleaseYear: "2015",
  },
  {
    Name: "Irelia",
    Image: "Irelia",
    Gender: "Female",
    Position: ["Middle", "Top"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Ivern",
    Image: "Ivern",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Freljord", "Ionia"],
    ReleaseYear: "2016",
  },
  {
    Name: "Janna",
    Image: "Janna",
    Gender: "Female",
    Position: ["Support"],
    Species: ["God", "Spirit"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima", "Zaun"],
    ReleaseYear: "2009",
  },
  {
    Name: "Jarvan IV",
    Image: "JarvanIV",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Demacia"],
    ReleaseYear: "2011",
  },
  {
    Name: "Jax",
    Image: "Jax",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Unknown"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Icathia", "Runeterra", "Shurima"],
    ReleaseYear: "2009",
  },
  {
    Name: "Jayce",
    Image: "Jayce",
    Gender: "Male",
    Position: ["Middle", "Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee", "Ranged"],
    Region: ["Piltover"],
    ReleaseYear: "2012",
  },
  {
    Name: "Jhin",
    Image: "Jhin",
    Gender: "Male",
    Position: ["Bottom"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ionia"],
    ReleaseYear: "2016",
  },
  {
    Name: "Jinx",
    Image: "Jinx",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Chemically Altered", "Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Zaun"],
    ReleaseYear: "2013",
  },
  {
    Name: "KSante",
    Image: "KSante",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shurima"],
    ReleaseYear: "2022",
  },
  {
    Name: "Kai'Sa",
    Image: "Kaisa",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Human", "Void-Being"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima", "Void"],
    ReleaseYear: "2018",
  },
  {
    Name: "Kalista",
    Image: "Kalista",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Undead"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Camavor", "Shadow Isles"],
    ReleaseYear: "2014",
  },
  {
    Name: "Karma",
    Image: "Karma",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ionia"],
    ReleaseYear: "2011",
  },
  {
    Name: "Karthus",
    Image: "Karthus",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Undead"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus", "Shadow Isles"],
    ReleaseYear: "2009",
  },
  {
    Name: "Kassadin",
    Image: "Kassadin",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Human", "Void-Being"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shurima", "Void"],
    ReleaseYear: "2009",
  },
  {
    Name: "Katarina",
    Image: "Katarina",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Human"],
    Resource: "Manaless",
    RangeType: ["Melee"],
    Region: ["Noxus"],
    ReleaseYear: "2009",
  },
  {
    Name: "Kayle",
    Image: "Kayle",
    Gender: "Female",
    Position: ["Top"],
    Species: ["Aspect", "Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Melee", "Ranged"],
    Region: ["Demacia", "Targon"],
    ReleaseYear: "2009",
  },
  {
    Name: "Kayn",
    Image: "Kayn",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Darkin", "Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ionia", "Noxus", "Runeterra", "Shurima"],
    ReleaseYear: "2017",
  },
  {
    Name: "Kennen",
    Image: "Kennen",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Yordle"],
    Resource: "Energy",
    RangeType: ["Ranged"],
    Region: ["Ionia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Kha'Zix",
    Image: "Khazix",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Void-Being"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Void"],
    ReleaseYear: "2012",
  },
  {
    Name: "Kindred",
    Image: "Kindred",
    Gender: "Other",
    Position: ["Jungle"],
    Species: ["God", "Spirit"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Runeterra"],
    ReleaseYear: "2015",
  },
  {
    Name: "Kled",
    Image: "Kled",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Yordle"],
    Resource: "Courage",
    RangeType: ["Melee"],
    Region: ["Noxus"],
    ReleaseYear: "2016",
  },
  {
    Name: "Kog'Maw",
    Image: "KogMaw",
    Gender: "Male",
    Position: ["Bottom"],
    Species: ["Void-Being"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Void"],
    ReleaseYear: "2010",
  },
  {
    Name: "LeBlanc",
    Image: "Leblanc",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus"],
    ReleaseYear: "2010",
  },
  {
    Name: "Lee Sin",
    Image: "LeeSin",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Human", "Spiritualist"],
    Resource: "Energy",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2011",
  },
  {
    Name: "Leona",
    Image: "Leona",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Aspect", "Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Targon"],
    ReleaseYear: "2011",
  },
  {
    Name: "Lillia",
    Image: "Lillia",
    Gender: "Female",
    Position: ["Jungle", "Top"],
    Species: ["Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2020",
  },
  {
    Name: "Lissandra",
    Image: "Lissandra",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Human", "Iceborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Freljord"],
    ReleaseYear: "2013",
  },
  {
    Name: "Lucian",
    Image: "Lucian",
    Gender: "Male",
    Position: ["Bottom"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Demacia", "Shadow Isles"],
    ReleaseYear: "2013",
  },
  {
    Name: "Lulu",
    Image: "Lulu",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bandle City"],
    ReleaseYear: "2012",
  },
  {
    Name: "Lux",
    Image: "Lux",
    Gender: "Female",
    Position: ["Middle", "Support"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Demacia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Malphite",
    Image: "Malphite",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Golem"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ixtal", "Shurima"],
    ReleaseYear: "2009",
  },
  {
    Name: "Malzahar",
    Image: "Malzahar",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Human", "Void-Being"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima", "Void"],
    ReleaseYear: "2010",
  },
  {
    Name: "Maokai",
    Image: "Maokai",
    Gender: "Male",
    Position: ["Jungle", "Support"],
    Species: ["Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shadow Isles"],
    ReleaseYear: "2011",
  },
  {
    Name: "Master Yi",
    Image: "MasterYi",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2009",
  },
  {
    Name: "Miss Fortune",
    Image: "MissFortune",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bilgewater"],
    ReleaseYear: "2010",
  },
  {
    Name: "Mordekaiser",
    Image: "Mordekaiser",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Revenant"],
    Resource: "Shield",
    RangeType: ["Melee"],
    Region: ["Noxus"],
    ReleaseYear: "2010",
  },
  {
    Name: "Morgana",
    Image: "Morgana",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Aspect", "Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Demacia", "Targon"],
    ReleaseYear: "2009",
  },
  {
    Name: "Nami",
    Image: "Nami",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Vastayan"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Runeterra"],
    ReleaseYear: "2012",
  },
  {
    Name: "Nasus",
    Image: "Nasus",
    Gender: "Male",
    Position: ["Top"],
    Species: ["God-Warrior"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shurima"],
    ReleaseYear: "2009",
  },
  {
    Name: "Nautilus",
    Image: "Nautilus",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Revenant"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Bilgewater"],
    ReleaseYear: "2012",
  },
  {
    Name: "Neeko",
    Image: "Neeko",
    Gender: "Female",
    Position: ["Middle", "Support"],
    Species: ["Vastayan"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ixtal"],
    ReleaseYear: "2018",
  },
  {
    Name: "Nidalee",
    Image: "Nidalee",
    Gender: "Female",
    Position: ["Jungle"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Melee", "Ranged"],
    Region: ["Ixtal"],
    ReleaseYear: "2009",
  },
  {
    Name: "Nilah",
    Image: "Nilah",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Bilgewater"],
    ReleaseYear: "2022",
  },
  {
    Name: "Nocturne",
    Image: "Nocturne",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Demon", "Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Runeterra"],
    ReleaseYear: "2011",
  },
  {
    Name: "Nunu & Willump",
    Image: "Nunu",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Human", "Yeti"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2009",
  },
  {
    Name: "Olaf",
    Image: "Olaf",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Human", "Iceborn"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2010",
  },
  {
    Name: "Orianna",
    Image: "Orianna",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Golem"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Piltover"],
    ReleaseYear: "2011",
  },
  {
    Name: "Ornn",
    Image: "Ornn",
    Gender: "Male",
    Position: ["Top"],
    Species: ["God", "Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2017",
  },
  {
    Name: "Pantheon",
    Image: "Pantheon",
    Gender: "Male",
    Position: ["Jungle", "Middle", "Support"],
    Species: ["Aspect", "Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Targon"],
    ReleaseYear: "2010",
  },
  {
    Name: "Poppy",
    Image: "Poppy",
    Gender: "Female",
    Position: ["Jungle", "Top"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Demacia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Pyke",
    Image: "Pyke",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Revenant"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Bilgewater"],
    ReleaseYear: "2018",
  },
  {
    Name: "Qiyana",
    Image: "Qiyana",
    Gender: "Female",
    Position: ["Jungle", "Middle"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ixtal"],
    ReleaseYear: "2019",
  },
  {
    Name: "Quinn",
    Image: "Quinn",
    Gender: "Female",
    Position: ["Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Demacia"],
    ReleaseYear: "2013",
  },
  {
    Name: "Rakan",
    Image: "Rakan",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Vastayan"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2017",
  },
  {
    Name: "Rammus",
    Image: "Rammus",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["God-Warrior"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shurima"],
    ReleaseYear: "2009",
  },
  {
    Name: "Rek'Sai",
    Image: "RekSai",
    Gender: "Female",
    Position: ["Jungle"],
    Species: ["Void-Being"],
    Resource: "Rage",
    RangeType: ["Melee"],
    Region: ["Shurima", "Void"],
    ReleaseYear: "2014",
  },
  {
    Name: "Rell",
    Image: "Rell",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Human", "Magically Altered", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Noxus"],
    ReleaseYear: "2020",
  },
  {
    Name: "Renata Glasc",
    Image: "Renata",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Chemically Altered", "Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Zaun"],
    ReleaseYear: "2022",
  },
  {
    Name: "Renekton",
    Image: "Renekton",
    Gender: "Male",
    Position: ["Top"],
    Species: ["God-Warrior"],
    Resource: "Fury",
    RangeType: ["Melee"],
    Region: ["Shurima"],
    ReleaseYear: "2011",
  },
  {
    Name: "Rengar",
    Image: "Rengar",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Vastayan"],
    Resource: "Ferocity",
    RangeType: ["Melee"],
    Region: ["Ixtal", "Shurima"],
    ReleaseYear: "2012",
  },
  {
    Name: "Riven",
    Image: "Riven",
    Gender: "Female",
    Position: ["Top"],
    Species: ["Human"],
    Resource: "Manaless",
    RangeType: ["Melee"],
    Region: ["Ionia", "Noxus"],
    ReleaseYear: "2011",
  },
  {
    Name: "Rumble",
    Image: "Rumble",
    Gender: "Male",
    Position: ["Middle", "Top"],
    Species: ["Yordle"],
    Resource: "Heat",
    RangeType: ["Melee"],
    Region: ["Bandle City"],
    ReleaseYear: "2011",
  },
  {
    Name: "Ryze",
    Image: "Ryze",
    Gender: "Male",
    Position: ["Middle", "Top"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Runeterra"],
    ReleaseYear: "2009",
  },
  {
    Name: "Samira",
    Image: "Samira",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus", "Shurima"],
    ReleaseYear: "2020",
  },
  {
    Name: "Sejuani",
    Image: "Sejuani",
    Gender: "Female",
    Position: ["Jungle", "Top"],
    Species: ["Human", "Iceborn"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2012",
  },
  {
    Name: "Senna",
    Image: "Senna",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Human", "Undead"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shadow Isles"],
    ReleaseYear: "2019",
  },
  {
    Name: "Seraphine",
    Image: "Seraphine",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Piltover", "Zaun"],
    ReleaseYear: "2020",
  },
  {
    Name: "Sett",
    Image: "Sett",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human", "Vastayan"],
    Resource: "Grit",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2020",
  },
  {
    Name: "Shaco",
    Image: "Shaco",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Runeterra"],
    ReleaseYear: "2009",
  },
  {
    Name: "Shen",
    Image: "Shen",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human", "Spiritualist"],
    Resource: "Energy",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Shyvana",
    Image: "Shyvana",
    Gender: "Female",
    Position: ["Jungle"],
    Species: ["Dragon", "Magically Altered"],
    Resource: "Fury",
    RangeType: ["Melee"],
    Region: ["Demacia"],
    ReleaseYear: "2011",
  },
  {
    Name: "Singed",
    Image: "Singed",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human", "Chemically Altered"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Piltover", "Zaun"],
    ReleaseYear: "2009",
  },
  {
    Name: "Sion",
    Image: "Sion",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Revenant"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Noxus"],
    ReleaseYear: "2009",
  },
  {
    Name: "Sivir",
    Image: "Sivir",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima"],
    ReleaseYear: "2009",
  },
  {
    Name: "Skarner",
    Image: "Skarner",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Brackern"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shurima"],
    ReleaseYear: "2011",
  },
  {
    Name: "Sona",
    Image: "Sona",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Demacia", "Ionia"],
    ReleaseYear: "2010",
  },
  {
    Name: "Soraka",
    Image: "Soraka",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Celestial"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ionia", "Targon"],
    ReleaseYear: "2009",
  },
  {
    Name: "Swain",
    Image: "Swain",
    Gender: "Female",
    Position: ["Middle", "Support"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus"],
    ReleaseYear: "2010",
  },
  {
    Name: "Sylas",
    Image: "Sylas",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Demacia", "Freljord"],
    ReleaseYear: "2019",
  },
  {
    Name: "Syndra",
    Image: "Syndra",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ionia"],
    ReleaseYear: "2012",
  },
  {
    Name: "Tahm Kench",
    Image: "TahmKench",
    Gender: "Male",
    Position: ["Support", "Top"],
    Species: ["Demon", "Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Bilgewater", "Runeterra"],
    ReleaseYear: "2015",
  },
  {
    Name: "Taliyah",
    Image: "Taliyah",
    Gender: "Female",
    Position: ["Jungle", "Middle"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima"],
    ReleaseYear: "2016",
  },
  {
    Name: "Talon",
    Image: "Talon",
    Gender: "Male",
    Position: ["Jungle", "Middle"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Noxus"],
    ReleaseYear: "2011",
  },
  {
    Name: "Taric",
    Image: "Taric",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Aspect", "Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Demacia", "Targon"],
    ReleaseYear: "2009",
  },
  {
    Name: "Teemo",
    Image: "Teemo",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bandle City"],
    ReleaseYear: "2009",
  },
  {
    Name: "Thresh",
    Image: "Thresh",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Undead"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shadow Isles"],
    ReleaseYear: "2013",
  },
  {
    Name: "Tristana",
    Image: "Tristana",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bandle City"],
    ReleaseYear: "2009",
  },
  {
    Name: "Trundle",
    Image: "Trundle",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Iceborn", "Troll"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2010",
  },
  {
    Name: "Tryndamere",
    Image: "Tryndamere",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human", "Magically Altered"],
    Resource: "Fury",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2009",
  },
  {
    Name: "Twisted Fate",
    Image: "TwistedFate",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bilgewater"],
    ReleaseYear: "2009",
  },
  {
    Name: "Twitch",
    Image: "Twitch",
    Gender: "Male",
    Position: ["Bottom"],
    Species: ["Chemically Altered", "Rat"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Zaun"],
    ReleaseYear: "2009",
  },
  {
    Name: "Udyr",
    Image: "Udyr",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Human", "Spiritualist"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord", "Ionia"],
    ReleaseYear: "2009",
  },
  {
    Name: "Urgot",
    Image: "Urgot",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Chemically Altered", "Cyborg", "Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Noxus", "Zaun"],
    ReleaseYear: "2010",
  },
  {
    Name: "Varus",
    Image: "Varus",
    Gender: "Male",
    Position: ["Bottom", "Middle"],
    Species: ["Darkin", "Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ionia", "Runeterra", "Shurima"],
    ReleaseYear: "2012",
  },
  {
    Name: "Vayne",
    Image: "Vayne",
    Gender: "Female",
    Position: ["Bottom", "Top"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Demacia"],
    ReleaseYear: "2011",
  },
  {
    Name: "Veigar",
    Image: "Veigar",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bandle City", "Runeterra"],
    ReleaseYear: "2009",
  },
  {
    Name: "Vel'Koz",
    Image: "Velkoz",
    Gender: "Male",
    Position: ["Middle", "Support"],
    Species: ["Void-Being"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Void"],
    ReleaseYear: "2014",
  },
  {
    Name: "Vex",
    Image: "Vex",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bandle City", "Shadow Isles"],
    ReleaseYear: "2021",
  },
  {
    Name: "Vi",
    Image: "Vi",
    Gender: "Female",
    Position: ["Jungle"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Piltover", "Zaun"],
    ReleaseYear: "2012",
  },
  {
    Name: "Viego",
    Image: "Viego",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Undead"],
    Resource: "Manaless",
    RangeType: ["Melee"],
    Region: ["Camavor", "Shadow Isles"],
    ReleaseYear: "2021",
  },
  {
    Name: "Viktor",
    Image: "Viktor",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Cyborg", "Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Piltover", "Zaun"],
    ReleaseYear: "2011",
  },
  {
    Name: "Vladimir",
    Image: "Vladimir",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Human", "Magically Altered"],
    Resource: "Bloodthirst",
    RangeType: ["Ranged"],
    Region: ["Camavor", "Noxus", "Shadow Isles"],
    ReleaseYear: "2010",
  },
  {
    Name: "Volibear",
    Image: "Volibear",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["God", "Spirit"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Freljord"],
    ReleaseYear: "2011",
  },
  {
    Name: "Warwick",
    Image: "Warwick",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Chemically Altered", "Cyborg", "Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Zaun"],
    ReleaseYear: "2009",
  },
  {
    Name: "Wukong",
    Image: "MonkeyKing",
    Gender: "Male",
    Position: ["Jungle", "Top"],
    Species: ["Vastayan"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2011",
  },
  {
    Name: "Xayah",
    Image: "Xayah",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Vastayan"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ionia"],
    ReleaseYear: "2017",
  },
  {
    Name: "Xerath",
    Image: "Xerath",
    Gender: "Male",
    Position: ["Middle", "Support"],
    Species: ["God-Warrior"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Shurima"],
    ReleaseYear: "2011",
  },
  {
    Name: "Xin Zhao",
    Image: "XinZhao",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Human"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Demacia", "Ionia", "Noxus"],
    ReleaseYear: "2010",
  },
  {
    Name: "Yasuo",
    Image: "Yasuo",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Human", "Magicborn"],
    Resource: "Flow",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2013",
  },
  {
    Name: "Yone",
    Image: "Yone",
    Gender: "Male",
    Position: ["Middle", "Top"],
    Species: ["Human", "Magically Altered"],
    Resource: "Manaless",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2020",
  },
  {
    Name: "Yorick",
    Image: "Yorick",
    Gender: "Male",
    Position: ["Top"],
    Species: ["Human", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Melee"],
    Region: ["Shadow Isles"],
    ReleaseYear: "2011",
  },
  {
    Name: "Yuumi",
    Image: "Yuumi",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Cat", "Magically Altered"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Bandle City"],
    ReleaseYear: "2019",
  },
  {
    Name: "Zac",
    Image: "Zac",
    Gender: "Male",
    Position: ["Jungle"],
    Species: ["Golem"],
    Resource: "Health costs",
    RangeType: ["Melee"],
    Region: ["Zaun"],
    ReleaseYear: "2013",
  },
  {
    Name: "Zed",
    Image: "Zed",
    Gender: "Male",
    Position: ["Middle"],
    Species: ["Human", "Magically Altered"],
    Resource: "Energy",
    RangeType: ["Melee"],
    Region: ["Ionia"],
    ReleaseYear: "2012",
  },
  {
    Name: "Zeri",
    Image: "Zeri",
    Gender: "Female",
    Position: ["Bottom"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Zaun"],
    ReleaseYear: "2022",
  },
  {
    Name: "Ziggs",
    Image: "Ziggs",
    Gender: "Male",
    Position: ["Bottom", "Middle"],
    Species: ["Yordle"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Zaun"],
    ReleaseYear: "2012",
  },
  {
    Name: "Zilean",
    Image: "Zilean",
    Gender: "Male",
    Position: ["Support"],
    Species: ["Human", "Magicborn"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Icathia", "Runeterra", "Shurima"],
    ReleaseYear: "2009",
  },
  {
    Name: "Zoe",
    Image: "Zoe",
    Gender: "Female",
    Position: ["Middle"],
    Species: ["Aspect", "Human"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Targon"],
    ReleaseYear: "2017",
  },
  {
    Name: "Zyra",
    Image: "Zyra",
    Gender: "Female",
    Position: ["Support"],
    Species: ["Unknown"],
    Resource: "Mana",
    RangeType: ["Ranged"],
    Region: ["Ixtal"],
    ReleaseYear: "2012",
  },
];
